tap "homebrew/bundle"
tap "homebrew/services"
tap "versent/taps"
tap "buo/cask-upgrade"

brew "mas"
brew "aws-iam-authenticator"
brew "erlang"
brew "elixir"
brew "git"
brew "gnupg"
brew "gobject-introspection"
brew "helm"
brew "kubernetes-cli", link: false
brew "kube-ps1"
brew "node"
brew "postgresql@14"
brew "pyenv"
brew "pyenv-virtualenvwrapper"
brew "rbenv"
brew "redis"
brew "tmux"
brew "vim"
brew "watch"
brew "saml2aws"
brew "yarn"

cask "docker"
cask "postman"
cask "corretto"
cask "spotify"
cask "visual-studio-code"
